flux_path: "black-forest-labs/FLUX.1-dev"
dtype: "bfloat16"

model:
  union_cond_attn: true
  add_cond_attn: false
  latent_lora: false

train:
  batch_size: 1
  accumulate_grad_batches: 2
  dataloader_workers: 8
  save_interval: 1000
  sample_interval: 100
  max_steps: 5000
  gradient_checkpointing: false
  save_path: "runs"

  model_type: "incontext_room"
  dataset:
    type: "incontext_room"
    target_size: 512
    image_size: 512
    padding: 0
    drop_text_prob: 0.0
    drop_image_prob: 0.0

  lora_config:
    r: 24
    lora_alpha: 24
    init_lora_weights: "gaussian"

  optimizer:
    type: "Prodigy"
    params:
      lr: 1.5
      use_bias_correction: true
      safeguard_warmup: true
      weight_decay: 0.01